pipeline {
  agent any
  stages {
    stage('Cloning') {
      steps {
        checkout scm
      }
    }
    stage('Building') {
      steps{
        script {
          println "==================="
          println "Building image"+env.BRANCH_NAME
          println "==================="
          dockerImage = docker.build("sunilmore690/express-app")

        }
      }
    }
    stage('Pushing') {
      steps{
        script {
          println "==================="
          println "Pushing image to Registry"
          println "==================="
          docker.withRegistry( '', 'jenkinsdockerhubcred' ) {
            println "Image Pushed"
            dockerImage.push("${env.BUILD_NUMBER}")
            dockerImage.push("${env.BRANCH_NAME}")
          }
        }
      }
    }    
  }
}